services:
  mysql:
    image: mysql:8.0
    container_name: dx-ktor-mysql
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dx_ktor}
      MYSQL_USER: ${MYSQL_USER:-ktor_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ktor_password}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dx-ktor-network

  redis:
    image: redis:7-alpine
    container_name: dx-ktor-redis
    restart: always
    ports:
      - "${REDIS_PORT:-6380}:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dx-ktor-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  dx-ktor-network:
    driver: bridge