ktor:
  application:
    modules:
      - com.kinto.dx.ApplicationKt.module
  deployment:
    port: 8080

database:
  url: "jdbc:mysql://prod-mysql.example.com:3306/dx_ktor_prod?useSSL=true&serverTimezone=UTC"
  driver: "com.mysql.cj.jdbc.Driver"
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  
  pool:
    maximumPoolSize: 20
    minimumIdle: 10
    idleTimeout: 600000
    connectionTimeout: 30000
    maxLifetime: 1800000
    leakDetectionThreshold: 60000

redis:
  host: "prod-redis.example.com"
  port: 6379
  password: ${REDIS_PASSWORD}
  database: 0
  
  pool:
    maxTotal: 50
    maxIdle: 20
    minIdle: 10