ktor:
  application:
    modules:
      - com.kinto.dx.ApplicationKt.module
  deployment:
    port: 8080

database:
  url: "jdbc:mysql://localhost:3307/dx_ktor?useSSL=false&serverTimezone=UTC"
  driver: "com.mysql.cj.jdbc.Driver"
  user: "ktor_user"
  password: "ktor_password123"
  
  pool:
    maximumPoolSize: 5
    minimumIdle: 2
    idleTimeout: 600000
    connectionTimeout: 30000
    maxLifetime: 1800000

redis:
  host: "localhost"
  port: 6380
  password: ""
  database: 0