ktor:
  application:
    modules:
      - com.kinto.dx.ApplicationKt.module
  deployment:
    port: 8080

database:
  url: "jdbc:mysql://stg-mysql.example.com:3306/dx_ktor_stg?useSSL=true&serverTimezone=UTC"
  driver: "com.mysql.cj.jdbc.Driver"
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  
  pool:
    maximumPoolSize: 15
    minimumIdle: 5
    idleTimeout: 600000
    connectionTimeout: 30000
    maxLifetime: 1800000

redis:
  host: "stg-redis.example.com"
  port: 6379
  password: ${REDIS_PASSWORD}
  database: 0